/****************************************************************************
 Name          : out_drv.h
 Author        : Autogenerated
 Copyright     : 2011-2020 by DIGI Vision Technologies Limited. All rights 
                 reserved. No part of this hardware description, either 
                 material or conceptual may be copied or distributed, 
                 transmitted, transcribed, stored in a retrieval system 
                 or translated into any human or computer language in 
                 any form by any means, electronic, mechanical, manual 
                 or otherwise, or disclosed to third parties without 
                 the express written permission of DIGI Vision 
                 Technologies Limited.
 Description   : 

 Program Type  : Autogenerated C -- do not edit

 Regconv       : 0.2_r110

 Generated from: dvt.def 
****************************************************************************/


#ifndef _OUT_DRV_H_
#define _OUT_DRV_H_

/*
	Register GR_VERSION
*/
#define DVT_DVT_GR_VERSION                                0x0000
#define DVT_GR_VERSION_SVN_MASK                           0xFFFFFFFF
#define DVT_GR_VERSION_SVN_SHIFT                          0
#define DVT_GR_VERSION_SVN_SIGNED                         0

/*
	Register GR_COMPANY_DIGI
*/
#define DVT_DVT_GR_COMPANY_DIGI                           0x0010
#define DVT_GR_COMPANY_DIGI_ASCII_MASK                    0xFFFFFFFF
#define DVT_GR_COMPANY_DIGI_ASCII_SHIFT                   0
#define DVT_GR_COMPANY_DIGI_ASCII_SIGNED                  0

/*
	Register GR_COMPANY_VISI
*/
#define DVT_DVT_GR_COMPANY_VISI                           0x0014
#define DVT_GR_COMPANY_VISI_ASCII_MASK                    0xFFFFFFFF
#define DVT_GR_COMPANY_VISI_ASCII_SHIFT                   0
#define DVT_GR_COMPANY_VISI_ASCII_SIGNED                  0

/*
	Register GR_COMPANY_ON
*/
#define DVT_DVT_GR_COMPANY_ON                             0x0018
#define DVT_GR_COMPANY_ON_ASCII_MASK                      0xFFFFFFFF
#define DVT_GR_COMPANY_ON_ASCII_SHIFT                     0
#define DVT_GR_COMPANY_ON_ASCII_SIGNED                    0

/*
	Register GR_COMPANY_HZCN
*/
#define DVT_DVT_GR_COMPANY_HZCN                           0x001C
#define DVT_GR_COMPANY_HZCN_ASCII_MASK                    0xFFFFFFFF
#define DVT_GR_COMPANY_HZCN_ASCII_SHIFT                   0
#define DVT_GR_COMPANY_HZCN_ASCII_SIGNED                  0

/*
	Register GR_IRQ_PORT
*/
#define DVT_DVT_GR_IRQ_PORT                               0x0100
#define DVT_GR_IRQ_PORT_HIGH_MASK                         0x00000001
#define DVT_GR_IRQ_PORT_HIGH_SHIFT                        0
#define DVT_GR_IRQ_PORT_HIGH_SIGNED                       0

/*
	Register GR_IRQ_CMD
*/
#define DVT_DVT_GR_IRQ_CMD                                0x0110
#define DVT_GR_IRQ_CMD_SIDE_INFO_MASK                     0xFFFFFF00
#define DVT_GR_IRQ_CMD_SIDE_INFO_SHIFT                    8
#define DVT_GR_IRQ_CMD_SIDE_INFO_SIGNED                   0

#define DVT_GR_IRQ_CMD_OP_MASK                            0x000000FF
#define DVT_GR_IRQ_CMD_OP_SHIFT                           0
#define DVT_GR_IRQ_CMD_OP_SIGNED                          0

/*
	Register GR_IRQ_DATA_SIZE
*/
#define DVT_DVT_GR_IRQ_DATA_SIZE                          0x0114
#define DVT_GR_IRQ_DATA_SIZE_BYTES_MASK                   0xFFFFFFFF
#define DVT_GR_IRQ_DATA_SIZE_BYTES_SHIFT                  0
#define DVT_GR_IRQ_DATA_SIZE_BYTES_SIGNED                 0

/*
	Register GR_IRQ_D0
*/
#define DVT_DVT_GR_IRQ_D0                                 0x0118
#define DVT_GR_IRQ_D0_SRC_ADDR_H_MASK                     0xFFFFFFFF
#define DVT_GR_IRQ_D0_SRC_ADDR_H_SHIFT                    0
#define DVT_GR_IRQ_D0_SRC_ADDR_H_SIGNED                   0

/*
	Register GR_IRQ_D1
*/
#define DVT_DVT_GR_IRQ_D1                                 0x011C
#define DVT_GR_IRQ_D1_SRC_ADDR_L_MASK                     0xFFFFFFFF
#define DVT_GR_IRQ_D1_SRC_ADDR_L_SHIFT                    0
#define DVT_GR_IRQ_D1_SRC_ADDR_L_SIGNED                   0

/*
	Register GR_IRQ_D2
*/
#define DVT_DVT_GR_IRQ_D2                                 0x0120
#define DVT_GR_IRQ_D2_DEST_ADDR_H_MASK                    0xFFFFFFFF
#define DVT_GR_IRQ_D2_DEST_ADDR_H_SHIFT                   0
#define DVT_GR_IRQ_D2_DEST_ADDR_H_SIGNED                  0

/*
	Register GR_IRQ_D3
*/
#define DVT_DVT_GR_IRQ_D3                                 0x0124
#define DVT_GR_IRQ_D3_DEST_ADDR_L_MASK                    0xFFFFFFFF
#define DVT_GR_IRQ_D3_DEST_ADDR_L_SHIFT                   0
#define DVT_GR_IRQ_D3_DEST_ADDR_L_SIGNED                  0

/*
	Register GR_MOS_CTRL
*/
#define DVT_DVT_GR_MOS_CTRL                               0x0400
#define DVT_GR_MOS_CTRL_SLAVE_MODE_MASK                   0x00000001
#define DVT_GR_MOS_CTRL_SLAVE_MODE_SHIFT                  0
#define DVT_GR_MOS_CTRL_SLAVE_MODE_SIGNED                 0

#define DVT_GR_MOS_CTRL_VS_HS_OEN_MASK                    0x00000010
#define DVT_GR_MOS_CTRL_VS_HS_OEN_SHIFT                   4
#define DVT_GR_MOS_CTRL_VS_HS_OEN_SIGNED                  0

#define DVT_GR_MOS_CTRL_IIC_SL_MASK                       0x00000F00
#define DVT_GR_MOS_CTRL_IIC_SL_SHIFT                      8
#define DVT_GR_MOS_CTRL_IIC_SL_SIGNED                     0

/*
	Register GR_MOS_FRAME
*/
#define DVT_DVT_GR_MOS_FRAME                              0x0404
#define DVT_GR_MOS_FRAME_VS_LINE_CNT_MASK                 0x0000FFFF
#define DVT_GR_MOS_FRAME_VS_LINE_CNT_SHIFT                0
#define DVT_GR_MOS_FRAME_VS_LINE_CNT_SIGNED               0

#define DVT_GR_MOS_FRAME_HS_INCK_CNT_MASK                 0x0FFF0000
#define DVT_GR_MOS_FRAME_HS_INCK_CNT_SHIFT                16
#define DVT_GR_MOS_FRAME_HS_INCK_CNT_SIGNED               0

/*
	Register GR_RAW_LOC_H
*/
#define DVT_DVT_GR_RAW_LOC_H                              0x0408
#define DVT_GR_RAW_LOC_H_SET_CNT_MASK                     0x00000FFF
#define DVT_GR_RAW_LOC_H_SET_CNT_SHIFT                    0
#define DVT_GR_RAW_LOC_H_SET_CNT_SIGNED                   0

#define DVT_GR_RAW_LOC_H_OFFSET_MASK                      0x0FFF0000
#define DVT_GR_RAW_LOC_H_OFFSET_SHIFT                     16
#define DVT_GR_RAW_LOC_H_OFFSET_SIGNED                    0

/*
	Register GR_RAW_LOC_V
*/
#define DVT_DVT_GR_RAW_LOC_V                              0x040C
#define DVT_GR_RAW_LOC_V_CNT_MASK                         0x00003FFF
#define DVT_GR_RAW_LOC_V_CNT_SHIFT                        0
#define DVT_GR_RAW_LOC_V_CNT_SIGNED                       0

#define DVT_GR_RAW_LOC_V_OFFSET_MASK                      0x3FFF0000
#define DVT_GR_RAW_LOC_V_OFFSET_SHIFT                     16
#define DVT_GR_RAW_LOC_V_OFFSET_SIGNED                    0

/*
	Register GR_AE_MANU
*/
#define DVT_DVT_GR_AE_MANU                                0x0500
#define DVT_GR_AE_MANU_EXP_MASK                           0x00000FFF
#define DVT_GR_AE_MANU_EXP_SHIFT                          0
#define DVT_GR_AE_MANU_EXP_SIGNED                         0

#define DVT_GR_AE_MANU_GAIN_MASK                          0x01FF0000
#define DVT_GR_AE_MANU_GAIN_SHIFT                         16
#define DVT_GR_AE_MANU_GAIN_SIGNED                        0

/*
	Register GR_RAW_STRIDE
*/
#define DVT_DVT_GR_RAW_STRIDE                             0x0800
#define DVT_GR_RAW_STRIDE_GENERAL_MASK                    0x000000FF
#define DVT_GR_RAW_STRIDE_GENERAL_SHIFT                   0
#define DVT_GR_RAW_STRIDE_GENERAL_SIGNED                  0

/*
	Register GR_RB_CTRL
*/
#define DVT_DVT_GR_RB_CTRL                                0x0810
#define DVT_GR_RB_CTRL_WR_BLOCKING_MASK                   0x00000001
#define DVT_GR_RB_CTRL_WR_BLOCKING_SHIFT                  0
#define DVT_GR_RB_CTRL_WR_BLOCKING_SIGNED                 0

#define DVT_GR_RB_CTRL_WR_INIT_IRQ_MASK                   0x00000100
#define DVT_GR_RB_CTRL_WR_INIT_IRQ_SHIFT                  8
#define DVT_GR_RB_CTRL_WR_INIT_IRQ_SIGNED                 0

/*
	Register GR_RB_ADDR
*/
#define DVT_DVT_GR_RB_ADDR                                0x0814
#define DVT_GR_RB_ADDR_BASE_MASK                          0xFFFFFFFF
#define DVT_GR_RB_ADDR_BASE_SHIFT                         0
#define DVT_GR_RB_ADDR_BASE_SIGNED                        0

/*
	Register GR_RB_STRIDE
*/
#define DVT_DVT_GR_RB_STRIDE                              0x0818
#define DVT_GR_RB_STRIDE_FRAME_MASK                       0x00FFFFFF
#define DVT_GR_RB_STRIDE_FRAME_SHIFT                      0
#define DVT_GR_RB_STRIDE_FRAME_SIGNED                     0

/*
	Register GR_RB_LOC
*/
#define DVT_DVT_GR_RB_LOC                                 0x081C
#define DVT_GR_RB_LOC_WR_MASK                             0x00000003
#define DVT_GR_RB_LOC_WR_SHIFT                            0
#define DVT_GR_RB_LOC_WR_SIGNED                           0

/*
	Register GR_RB_SLOT
*/
#define DVT_DVT_GR_RB_SLOT                                0x0820
#define DVT_GR_RB_SLOT_TABLE_MASK                         0x0000000F
#define DVT_GR_RB_SLOT_TABLE_SHIFT                        0
#define DVT_GR_RB_SLOT_TABLE_SIGNED                       0

/*
	Register GR_RGB_STRIDE
*/
#define DVT_DVT_GR_RGB_STRIDE                             0x0840
#define DVT_GR_RGB_STRIDE_GENERAL_MASK                    0x000000FF
#define DVT_GR_RGB_STRIDE_GENERAL_SHIFT                   0
#define DVT_GR_RGB_STRIDE_GENERAL_SIGNED                  0

/*
	Register GR_CB_CTRL
*/
#define DVT_DVT_GR_CB_CTRL                                0x0850
#define DVT_GR_CB_CTRL_WR_BLOCKING_MASK                   0x00000001
#define DVT_GR_CB_CTRL_WR_BLOCKING_SHIFT                  0
#define DVT_GR_CB_CTRL_WR_BLOCKING_SIGNED                 0

#define DVT_GR_CB_CTRL_WR_INIT_IRQ_MASK                   0x00000100
#define DVT_GR_CB_CTRL_WR_INIT_IRQ_SHIFT                  8
#define DVT_GR_CB_CTRL_WR_INIT_IRQ_SIGNED                 0

/*
	Register GR_CB_ADDR
*/
#define DVT_DVT_GR_CB_ADDR                                0x0854
#define DVT_GR_CB_ADDR_BASE_MASK                          0xFFFFFFFF
#define DVT_GR_CB_ADDR_BASE_SHIFT                         0
#define DVT_GR_CB_ADDR_BASE_SIGNED                        0

/*
	Register GR_CB_STRIDE
*/
#define DVT_DVT_GR_CB_STRIDE                              0x0858
#define DVT_GR_CB_STRIDE_FRAME_MASK                       0x00FFFFFF
#define DVT_GR_CB_STRIDE_FRAME_SHIFT                      0
#define DVT_GR_CB_STRIDE_FRAME_SIGNED                     0

/*
	Register GR_CB_LOC
*/
#define DVT_DVT_GR_CB_LOC                                 0x085C
#define DVT_GR_CB_LOC_WR_MASK                             0x00000003
#define DVT_GR_CB_LOC_WR_SHIFT                            0
#define DVT_GR_CB_LOC_WR_SIGNED                           0

/*
	Register GR_CB_SLOT
*/
#define DVT_DVT_GR_CB_SLOT                                0x0860
#define DVT_GR_CB_SLOT_TABLE_MASK                         0x0000000F
#define DVT_GR_CB_SLOT_TABLE_SHIFT                        0
#define DVT_GR_CB_SLOT_TABLE_SIGNED                       0

#endif /* _OUT_DRV_H_ */

/*****************************************************************************
 End of file (out_drv.h)
*****************************************************************************/

